namespace Aqueous.Features.Compositor.River;

/// <summary>
/// Stable identifier for every built-in chord action that <see cref="RiverWindowManagerClient"/>
/// can dispatch. Promoted out of the nested-enum declaration.
/// </summary>
internal enum KeyBindingAction
{
    ToggleStartMenu,
    SpawnTerminal,
    CloseFocused,
    CycleFocus,
    FocusLeft,
    FocusRight,
    FocusDown,
    FocusUp,
    ScrollViewportLeft,
    ScrollViewportRight,
    MoveWindowLeft,
    MoveWindowRight,
    MoveWindowUp,
    MoveWindowDown,
    ReloadConfig,
    ReloadRules,
    SetLayoutPrimary,
    SetLayoutSecondary,
    SetLayoutTertiary,
    SetLayoutQuaternary,
    FocusWorkspace1,
    FocusWorkspace2,
    FocusWorkspace3,
    FocusWorkspace4,
    FocusWorkspace5,
    FocusWorkspace6,
    FocusWorkspace7,
    FocusWorkspace8,
    FocusWorkspace9,
    MoveToWorkspace1,
    MoveToWorkspace2,
    MoveToWorkspace3,
    MoveToWorkspace4,
    MoveToWorkspace5,
    MoveToWorkspace6,
    MoveToWorkspace7,
    MoveToWorkspace8,
    MoveToWorkspace9,
    FocusWorkspaceUp,
    FocusWorkspaceDown,
    FocusPreviousWorkspace,
    MoveToWorkspaceUp,
    MoveToWorkspaceDown,
    MoveWorkspaceUp,
    MoveWorkspaceDown,
    FocusOutputLeft,
    FocusOutputRight,
    MoveToOutputLeft,
    MoveToOutputRight,
    ToggleFullscreen,
    ToggleMaximize,
    ToggleFloating,
    ToggleMinimize,
    UnminimizeLast,
    ToggleScratchpad,
    SendToScratchpad,
    Custom,
    LockScreen,
    UntrapPointer,
}
