[core]
plugins = autostart
xwayland = 0

[autostart]
#greeter = /usr/bin/aqueous-greeter
greeter = /home/zoey/RiderProjects/Aqueous/AqueousGreeter/bin/Debug/net10.0/AqueousGreeter
autostart_wf_shell = false
